export type {
  OpenDocumentResult,
  RecentFile,
  TexBlock,
  TexRecoverableSession,
  TexDocumentPayload,
  TexRouteHeading,
  TexSendInsertMode,
  TexSendRequest,
  TexSendResult,
  TexSessionAttachResult,
  TexSessionOpenResult,
  TexSessionRouteTarget,
  TexSessionOwnerConflict,
  TexSessionSnapshot,
  TexSessionSummary,
  TexSessionUpdatedEvent,
  TexSpeechTargetState,
  TexSessionUpdateArgs,
  TexTextRun,
} from "../../../tex-shared/src/document";
